import Link from 'next/link';
import './globals.css';
import Topbar from './components/Topbar';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body class='bg-slate-500 text-white'>
				<Topbar />
				{children}
			</body>
		</html>
	);
}
export default RootLayout;
